import React from "react";

import {
  SoundSetting,
  ThemeSetting,
  SpeedTestLevelSetting,
  SpeedTestDataSetting,
} from "@/containers/Setting";
import Head from "next/head";

const SettingPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Cài đặt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="py-lg">
        <div className="m-lg">
          <div className="border-l-4 border-contrast-secondary border-opacity-87 pl-sm">
            <h2 className="text-contrast-secondary text-opacity-87 text-headline-2 font-semibold">
              Âm thanh và chủ đề
            </h2>
          </div>
          <div className="mx-md my-lg">
            <SoundSetting />
          </div>
          <div className="mx-md my-lg">
            <ThemeSetting />
          </div>
        </div>
        <div className="m-lg">
          <div className="border-l-4 border-contrast-secondary border-opacity-87 pl-sm">
            <h2 className="text-contrast-secondary text-opacity-87 text-headline-2 font-semibold">
              Kiểm tra tốc độ gõ
            </h2>
          </div>
          <div className="mx-md my-lg">
            <SpeedTestLevelSetting />
          </div>
          <div className="mx-md my-lg">
            <SpeedTestDataSetting />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
};

export default SettingPage;
