import React from "react";

import { SoundSetting, ThemeSetting, LessonLevelSetting } from "@/containers/Setting";
import Head from "next/head";

const SettingPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Cài đặt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-lg">
        <div className="border-l-4 border-contrast-secondary border-opacity-87 pl-sm">
          <h2 className="text-contrast-secondary text-opacity-87 text-headline-2 font-semibold">
            Âm thanh và chủ đề
          </h2>
        </div>
        <div className="m-md">
          <SoundSetting />
        </div>
        <div className="m-md">
          <ThemeSetting />
        </div>
      </div>
    </React.Fragment>
  );
};

export default SettingPage;
