import Head from "next/head";
import React from "react";

import { SpeedTestProvider } from "@/modules/speedtest";
import { SpeedTestPractice, SpeedTestControl, SpeedTestStatistical } from "@/containers/SpeedTest";

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpeedTestProvider>
        <div className="m-lg">
          <SpeedTestPractice />
        </div>
        <div className="m-lg">
          <SpeedTestControl />
        </div>
        <div className="m-lg my-0 py-lg">
          <SpeedTestStatistical />
        </div>
      </SpeedTestProvider>
    </React.Fragment>
  );
}
